Bring_My_Book_V2/Models/Batch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bring_My_Book_V2.Models
{
    public class Batch
    {
        public int   BatchId{get; set;}
        public int BatchYear { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}

Bring_My_Book_V2/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bring_My_Book_V2.Models
{
    public class Post
    {
        public int PostId { get; set; }

        [Required]
        [Display(Name="Product Name")]
        public string PostName {get; set;}

        [Required]
        [Display(Name = "Description")]
        public string PostDescription { get; set; }

        public DateTime PostDateTime {get; set;}

        public string PostType { get; set; }
        public DateTime PostUpdateTime { get; set; }
        public int TotalSell { get; set; }

        [Required]
        [Display(Name= "Quantity")]
        public int PostQuantity { get; set; }
        public List<User> Buyers { get; set; }
        public List<int> PostBuyers { get; set; }


        // type buy sell
        //update time
        //image load
        //if sell type amount of product
        //public List<int> buyers

        public double Price { get; set; }
        public User PostUser { get; set; }
        public string PostDept { get; set; }
        public int PostBatch { get; set; }
        public int BuyerId { get; set; }
        public bool check { get; set; }
        public ICollection<int> UserInterestedId { get; set; }
        public List<int> UserInterestedListId { get; set; }
 

    }
}

Bring_My_Book_V2/Controllers/BatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bring_My_Book_V2.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.ObjectModel;
using System.Security.Claims;
using Bring_My_Book_V2.Controllers;

namespace Bring_My_Book_V2.Controllers
{
    public class BatchController : Controller
    {
        // GET: Batch
        private ApplicationDbContext context = new ApplicationDbContext();
        User userInfo;
        public BatchController ()
        {
            string userId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            userInfo = context.UserInfo.FirstOrDefault(user => user.UserIdentityId == userId);
        }
        public ActionResult Index()
        {
            var posts = new Collection<Post>();
            //foreach (var item in context.Posts)
            //    posts.Add(item);
            var dummy = new Collection<Post>() {
            new Post{PostId = 1, PostBatch = 2004, PostDept = "Economics", PostDescription = "adlkfaldkfadsf adfsads fdsf",
                    PostUser = userInfo, PostDateTime = new DateTime(2016, 1, 21)},
            new Post{PostId = 2, PostBatch = 2012, PostDept = "Anthropology", PostDescription = "Paper donshon e donshito",
                    PostUser = userInfo, PostDateTime = new DateTime(2016, 9, 23)},
            new Post{PostId = 3, PostBatch = 2002, PostDept = "CSE", PostDescription = "Kaldi or khaldi thesis pass korte hobe",
                    PostUser = userInfo, PostDateTime = new DateTime(2011, 1, 3)},
            new Post{PostId = 4, PostBatch = 1999, PostDept = "CEP", PostDescription = "Deep speech",
                    PostUser = userInfo, PostDateTime = new DateTime(2012, 9, 17)},
            
            new Post{PostId = 5, PostBatch = 1998, PostDept = "BBA", PostDescription = "Masum sir 100 taka",
                    PostUser = userInfo, PostDateTime = new DateTime(2011, 9, 17)}
            
            };

            ViewBag.TotalPost = dummy.Count();
            dummy.OrderByDescending(m => m.PostDateTime.Year).
            ThenByDescending(m => m.PostDateTime.Month).ThenByDescending(m => m.PostDateTime.Day);
            //dummy.OrderBy(d => d.PostDateTime);
            return View(dummy);
        }
    }
}

Bring_My_Book_V2/Views/Batch/Post.cshtml
@model Bring_My_Book_V2.Models.Post
@{
    ViewBag.Title = "Post";
}

<header class="page-title pt-small pt-dark">
    <div class="container">
        <h1>@ViewBag.Title</h1>
    </div>
</header>

<div class="login-1">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-3 col-md-6">

                <!-- Log in -->
                <div class="panel-group" id="login-accordion" role="tablist" aria-multiselectable="true">
                    <div class="panel top-panel panel-default">
                        <div class="panel-heading" role="tab" id="headingOne">
                            <h4 class="panel-title text-center">
                                Post What you need
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                            <div class="panel-body">

                                <div class="form-login">
                                    @using (Html.BeginForm("Post", "Batch", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                                    {
                                        @Html.AntiForgeryToken()

                                        @Html.ValidationSummary("", new { @class = "text-danger" })
                                           <!-- Textarea -->

                                        <div class="form-group">
                                            <div class="col-md-4">
                                                @Html.LabelFor(m => m.PostDescription, new { @class = "col-md-4 control-label" })
                                            </div>

                                            <div class="col-md-8">
                                                @Html.TextAreaFor(m => m.PostDescription, new { @class = "form-control", @placeholder = "Write details about your post", @rows = "9" })
                                            </div>

                                        </div>


                                        <div class="form-group">
                                            <div class="col-md-4">
                                                @Html.LabelFor(m => m.Price, new { @class = "col-md-4 control-label" })
                                            </div>
                                            <div class="col-md-8">
                                                @Html.TextBoxFor(m => m.Price, new { @class = "form-control", @type = "number", @min = "0" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-offset-4 col-md-8">
                                                <input type="submit" class="btn btn-default" value="Post" />
                                            </div>
                                        </div>
                                    }
                                </div><!-- / .form-login -->

                            </div><!-- / .panel-body -->
                        </div><!-- / .panel-collapse -->
                    </div><!-- / .panel -->

                </div><!-- / #login-accordion .panel-group -->


            </div><!-- / .col-md-6 .col-md-offset-3 -->
        </div><!-- / .row -->
    </div>
</div>






@section scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>
        $(document).ready(function () {
            $("#student").click(function () {
                $("#teacher1").css("display", "none");
                $("#student1").css("display", "block");
            });
            $("#teacher").click(function () {
                $("#student1").css("display", "none");
                $("#teacher1").css("display", "block");
            });
        });
    </script>

}